CREATE TABLE	dbo.DimDate (
DateID						INT				NOT NULL	IDENTITY(1,1),
FullDate					DATE			NOT NULL,
CalendarYearNumber			INT				NOT NULL,
CalendarYearName			NVARCHAR(50)	NOT NULL,
CalendarYearQuarterNumber	INT				NOT NULL,
CalendarYearQuarterName		NVARCHAR(50)	NOT NULL,
CalendarYearMonthNumber		INT				NOT NULL,
CalendarYearMonthName		NVARCHAR(50)	NOT NULL,
CalendarQuarterNumber		INT				NOT NULL,
CalendarQuarterName			NVARCHAR(50)	NOT NULL,
CalendarMonthNumber			INT				NOT NULL,
CalendarMonthName			NVARCHAR(50)	NOT NULL,
CalendarWeekNumber			INT				NOT NULL,
CalendarWeekName			NVARCHAR(50)	NOT NULL,
CalendarWeekofQuarterNumber INT				NOT NULL,
CalendarWeekofQuarterName	NVARCHAR(50)	NOT NULL,
CalendarDayName				NVARCHAR(50)	NOT NULL,
CalendarDayofYearNumber		INT				NOT NULL,
CalendarDayOfYearName		NVARCHAR(50)	NOT NULL,
CalendarDayOfQuarterNumber	INT				NOT NULL,
CalendarDayOfQuarterName	NVARCHAR(50)	NOT NULL,
CalendarDayOfWeekNumber		INT				NOT NULL,
CalendarDayOfWeekName		NVARCHAR(10)	NOT NULL,
FiscalYearNumber			INT				NOT NULL,
FiscalYearName				NVARCHAR(50)	NOT NULL,
FiscalYearQuarterNumber		INT				NOT NULL,
FiscalYearQuarterName		NVARCHAR(50)	NOT NULL,
FiscalYearMonthNumber		INT				NOT NULL,
FiscalYearMonthName			NVARCHAR(50)	NOT NULL,
FiscalQuarterNumber			INT				NOT NULL,
FiscalQuarterName			NVARCHAR(50)	NOT NULL,
FiscalMonthNumber			INT				NOT NULL,
FiscalMonthName				NVARCHAR(50)	NOT NULL,
FiscalWeekNumber			INT				NOT NULL,
FiscalWeekName				NVARCHAR(50)	NOT NULL,

)